development:
  contact_email: 'zmalik [at] gsd.uwaterloo.ca'
  exception_notification_email: zmalik@gsd.uwaterloo.ca
  lex_summary: lexrank
  email_summary: email
  email_markers_example:
    user_name: Mark Ward
    experiment_title: 'Bug Summary Evaluation'
    experiment_start_at: 'on 03/24/2012 at 05:00 PM'
    experiment_end_at: 'on 04/04/2012 at 12:30 AM'
    bug_report_id: 34546
    bug_report_title: 'FTBFS: gcc-4.0 got ICE when compiling glibc 2.3.5-2 in experimental on m68k'
    summary_link: 'http://lebu.uwaterloo.ca/survey/286_43adc7d8fbbfaf04-1457/access'
  email_markers_mapping:
    participant:
      user_name: name
      summary_link: access_token
    experiment:
      experiment_title: title
      experiment_start_at: start_at
      experiment_end_at: end_at
    bug_report:
      bug_report_id: bug_identifier
      bug_report_title: title

test:
  contact_email: 'zmalik [at] gsd.uwaterloo.ca'
  exception_notification_email: zmalik@gsd.uwaterloo.ca
  lex_summary: lexrank
  email_summary: email
  email_markers_example:
    user_name: Mark Ward
    experiment_title: 'Bug Summary Evaluation'
    experiment_start_at: 'on 03/24/2012 at 05:00 PM'
    experiment_end_at: 'on 04/04/2012 at 12:30 AM'
    bug_report_id: 34546
    bug_report_title: 'FTBFS: gcc-4.0 got ICE when compiling glibc 2.3.5-2 in experimental on m68k'
    summary_link: 'http://lebu.uwaterloo.ca/survey/286_43adc7d8fbbfaf04-1457/access'
  email_markers_mapping:
    participant:
      user_name: name
      summary_link: access_token
    experiment:
      experiment_title: title
      experiment_start_at: start_at
      experiment_end_at: end_at
    bug_report:
      bug_report_id: bug_identifier
      bug_report_title: title

production:
  contact_email: 'zmalik [at] gsd.uwaterloo.ca'
  exception_notification_email: zmalik@gsd.uwaterloo.ca
  lex_summary: lexrank
  email_summary: email
  email_markers_example:
    user_name: Mark Ward
    experiment_title: 'Bug Summary Evaluation'
    experiment_start_at: 'on 03/24/2012 at 05:00 PM'
    experiment_end_at: 'on 04/04/2012 at 12:30 AM'
    bug_report_id: 34546
    bug_report_title: 'FTBFS: gcc-4.0 got ICE when compiling glibc 2.3.5-2 in experimental on m68k'
    summary_link: 'http://lebu.uwaterloo.ca/survey/286_43adc7d8fbbfaf04-1457/access'
  email_markers_mapping:
    participant:
      user_name: name
      summary_link: access_token
    experiment:
      experiment_title: title
      experiment_start_at: start_at
      experiment_end_at: end_at
    bug_report:
      bug_report_id: bug_identifier
      bug_report_title: title

